%{
#include<iostream>
#include<cstdlib>
#include<string>

#define YYDEBUG 1

using namespace std;

extern int yylex();

void yyerror(string s){
    cerr<<s<<endl;
    exit(EXIT_FAILURE);
}
%}

%token DATE ID

%%

program : program naredba ';'         {}
        | naredba         ';'         {}
        ;

naredba : DATE                        {}
        ;
%%

int main(){
    yydebug=0;
    yyparse();
}
